// Sensitive CloudTrail events - the DEFAULT set behind the "Sensitive only"
// filter and the row highlight. Curated from a per-service classification (10 AWS
// domains): every security-relevant event at HIGH or MEDIUM severity (rule:
// severity !== "low" - GetSecretValue, AssumeRole, CreateUser, StopLogging, …).
// Low-severity recon reads (Describe*/List*/Get* floods) are excluded.
//
// This is the BASELINE. The user tunes it in Settings (see api/settings.ts:
// effectiveSensitive), which layers a persisted add/remove delta on top - so the
// app reads the EFFECTIVE set, and DEFAULT_SENSITIVE_APIS/isSensitive are only the
// default. SENSITIVE_INFO powers the editor rows (service/category/severity/why).
//
// GENERATED - edit scripts/sensitive-events.json and run scripts/gen-sensitive.mjs.

export interface SensitiveInfo {
  service: string;
  category: string; // credential-access, privilege-escalation, persistence, defense-evasion, discovery, lateral-movement, exfiltration, impact, data-access
  severity: "high" | "medium" | "low";
  defaultFlag: boolean; // catalog metadata (the tighter "always warrants a look" subset); not used for badging
  note: string; // why it's sensitive / the context that makes it matter
}

export const DEFAULT_SENSITIVE_APIS = new Set<string>([
  "EnableRegion",
  "PutAlternateContact",
  "PutContactInformation",
  "ImportCertificate",
  "DeleteBackupPlan",
  "DeleteBackupVault",
  "DeleteRecoveryPoint",
  "PutBackupVaultAccessPolicy",
  "CreateComputeEnvironment",
  "RegisterJobDefinition",
  "CreateStack",
  "CreateStackInstances",
  "UpdateStack",
  "DeleteEventDataStore",
  "DeleteTrail",
  "PutEventSelectors",
  "StopLogging",
  "UpdateTrail",
  "DeleteAlarms",
  "DisableAlarmActions",
  "AdminAddUserToGroup",
  "AdminCreateUser",
  "AdminSetUserPassword",
  "SetUserPoolMfaConfig",
  "UpdateUserPoolClient",
  "DeleteConfigRule",
  "DeleteConfigurationRecorder",
  "DeleteDeliveryChannel",
  "StopConfigurationRecorder",
  "DeleteLandingZone",
  "DisableControl",
  "DeleteBackup",
  "DeleteTable",
  "ExportTableToPointInTime",
  "RestoreTableFromBackup",
  "RestoreTableToPointInTime",
  "Scan",
  "UpdateContinuousBackups",
  "AcceptVpcPeeringConnection",
  "AttachInternetGateway",
  "AuthorizeSecurityGroupEgress",
  "AuthorizeSecurityGroupIngress",
  "CopySnapshot",
  "CreateImage",
  "CreateKeyPair",
  "CreateNetworkAclEntry",
  "CreateRoute",
  "CreateSnapshot",
  "CreateTrafficMirrorSession",
  "CreateTrafficMirrorTarget",
  "CreateTransitGatewayVpcAttachment",
  "CreateVpcPeeringConnection",
  "DeleteFlowLogs",
  "DeleteNetworkAclEntry",
  "DisableEbsEncryptionByDefault",
  "GetPasswordData",
  "ImportKeyPair",
  "ModifyImageAttribute",
  "ModifyInstanceAttribute",
  "ModifyNetworkInterfaceAttribute",
  "ModifySnapshotAttribute",
  "ReplaceRoute",
  "RunInstances",
  "SharedSnapshotCopyInitiated",
  "SharedSnapshotVolumeCreated",
  "TerminateInstances",
  "PutImage",
  "SetRepositoryPolicy",
  "CreateService",
  "ExecuteCommand",
  "RegisterTaskDefinition",
  "RunTask",
  "UpdateService",
  "CreateAccessPoint",
  "CreateMountTarget",
  "PutFileSystemPolicy",
  "AssociateAccessPolicy",
  "CreateAccessEntry",
  "CreateCluster",
  "UpdateClusterConfig",
  "DeleteRule",
  "PutPermission",
  "PutRule",
  "PutTargets",
  "CreateFilter",
  "CreateIPSet",
  "DeleteDetector",
  "DeletePublishingDestination",
  "DisassociateMembers",
  "UpdateDetector",
  "AddClientIDToOpenIDConnectProvider",
  "AddRoleToInstanceProfile",
  "AddUserToGroup",
  "AttachGroupPolicy",
  "AttachRolePolicy",
  "AttachUserPolicy",
  "ChangePassword",
  "CreateAccessKey",
  "CreateLoginProfile",
  "CreateOpenIDConnectProvider",
  "CreatePolicy",
  "CreatePolicyVersion",
  "CreateRole",
  "CreateSAMLProvider",
  "CreateServiceSpecificCredential",
  "CreateUser",
  "CreateVirtualMFADevice",
  "DeactivateMFADevice",
  "DeleteAccountPasswordPolicy",
  "DeleteLoginProfile",
  "DeleteRole",
  "DeleteRolePermissionsBoundary",
  "DeleteUser",
  "DeleteUserPermissionsBoundary",
  "DeleteVirtualMFADevice",
  "EnableMFADevice",
  "GetAccountAuthorizationDetails",
  "PutGroupPolicy",
  "PutRolePolicy",
  "PutUserPermissionsBoundary",
  "PutUserPolicy",
  "SetDefaultPolicyVersion",
  "SimulatePrincipalPolicy",
  "UpdateAccountPasswordPolicy",
  "UpdateAssumeRolePolicy",
  "UpdateLoginProfile",
  "UpdateOpenIDConnectProviderThumbprint",
  "UpdateSAMLProvider",
  "UploadSigningCertificate",
  "CreateGroupMembership",
  "Disable",
  "CreateGrant",
  "Decrypt",
  "DisableKey",
  "DisableKeyRotation",
  "ImportKeyMaterial",
  "PutKeyPolicy",
  "ScheduleKeyDeletion",
  "AddLayerVersionPermission",
  "AddPermission",
  "CreateEventSourceMapping",
  "CreateFunction",
  "CreateFunctionUrlConfig",
  "UpdateFunctionCode",
  "UpdateFunctionConfiguration",
  "DeleteLogGroup",
  "DeleteLogStream",
  "DeleteMetricFilter",
  "DeleteSubscriptionFilter",
  "PutRetentionPolicy",
  "DisableMacie",
  "UpdateMacieSession",
  "AcceptHandshake",
  "AttachPolicy",
  "CloseAccount",
  "CreateAccount",
  "DeletePolicy",
  "DeregisterDelegatedAdministrator",
  "DetachPolicy",
  "DisableAWSServiceAccess",
  "DisablePolicyType",
  "EnableAWSServiceAccess",
  "InviteAccountToOrganization",
  "LeaveOrganization",
  "MoveAccount",
  "RegisterDelegatedAdministrator",
  "RemoveAccountFromOrganization",
  "UpdatePolicy",
  "AcceptResourceShareInvitation",
  "AssociateResourceShare",
  "CreateResourceShare",
  "AddRoleToDBCluster",
  "AddRoleToDBInstance",
  "CopyDBClusterSnapshot",
  "CopyDBSnapshot",
  "CreateDBClusterSnapshot",
  "CreateDBSnapshot",
  "DeleteDBCluster",
  "DeleteDBInstance",
  "DeleteDBSnapshot",
  "DownloadDBLogFilePortion",
  "ModifyDBCluster",
  "ModifyDBClusterSnapshotAttribute",
  "ModifyDBInstance",
  "ModifyDBSnapshotAttribute",
  "RestoreDBClusterFromSnapshot",
  "RestoreDBClusterToPointInTime",
  "RestoreDBInstanceFromDBSnapshot",
  "RestoreDBInstanceToPointInTime",
  "StartExportTask",
  "AuthorizeSnapshotAccess",
  "CreateClusterSnapshot",
  "DeleteCluster",
  "EnableSnapshotCopy",
  "GetClusterCredentials",
  "ModifyCluster",
  "ModifyClusterIamRoles",
  "RestoreFromClusterSnapshot",
  "ChangeResourceRecordSets",
  "DeleteHostedZone",
  "DisableDomainTransferLock",
  "TransferDomainToAnotherAwsAccount",
  "UpdateDomainNameservers",
  "CopyObject",
  "DeleteBucket",
  "DeleteBucketEncryption",
  "DeleteBucketPolicy",
  "DeleteBucketPublicAccessBlock",
  "DeleteObjects",
  "PutAccessPointPolicy",
  "PutBucketAcl",
  "PutBucketEncryption",
  "PutBucketLifecycle",
  "PutBucketLogging",
  "PutBucketPolicy",
  "PutBucketPublicAccessBlock",
  "PutBucketReplication",
  "PutBucketVersioning",
  "PutBucketWebsite",
  "PutObjectAcl",
  "PutObjectLockConfiguration",
  "BatchGetSecretValue",
  "DeleteSecret",
  "GetSecretValue",
  "ListSecrets",
  "PutResourcePolicy",
  "PutSecretValue",
  "ReplicateSecretToRegions",
  "BatchDisableStandards",
  "DisableSecurityHub",
  "PutIdentityPolicy",
  "UpdateAccountSendingEnabled",
  "VerifyDomainIdentity",
  "VerifyEmailIdentity",
  "DeleteProtection",
  "ConsoleLogin",
  "PasswordRecoveryCompleted",
  "PasswordRecoveryRequested",
  "SwitchRole",
  "SetTopicAttributes",
  "Subscribe",
  "CreateActivation",
  "CreateDocument",
  "GetParameter",
  "GetParameters",
  "GetParametersByPath",
  "ModifyDocumentPermission",
  "PutParameter",
  "SendCommand",
  "StartAutomationExecution",
  "StartSession",
  "UpdateDocument",
  "AttachCustomerManagedPolicyReferenceToPermissionSet",
  "AttachManagedPolicyToPermissionSet",
  "CreateAccountAssignment",
  "CreatePermissionSet",
  "ProvisionPermissionSet",
  "PutInlinePolicyToPermissionSet",
  "PutPermissionsBoundaryToPermissionSet",
  "UpdateInstanceAccessControlAttributeConfiguration",
  "AssumeRole",
  "AssumeRoleWithSAML",
  "AssumeRoleWithWebIdentity",
  "GetFederationToken",
  "DeleteLoggingConfiguration",
  "DeleteWebACL",
  "DisassociateWebACL",
  "UpdateWebACL",
]);

// Per-event detail (service, category, severity, and the "why") - powers the
// Settings sensitive-events editor and hover tooltips.
export const SENSITIVE_INFO: Record<string, SensitiveInfo> = {
  "EnableRegion": { service: "account", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Enabling a dormant region is often legitimate expansion; sensitive when an attacker enables an unused region to operate where monitoring/guardrails are absent." },
  "PutAlternateContact": { service: "account", category: "persistence", severity: "medium", defaultFlag: false, note: "Routine for ops; sensitive when billing/security/operations contacts are repointed to attacker addresses to divert notifications." },
  "PutContactInformation": { service: "account", category: "persistence", severity: "medium", defaultFlag: true, note: "Changing primary account contact/address is rare and a classic account-takeover / recovery-abuse precursor." },
  "ImportCertificate": { service: "acm", category: "persistence", severity: "medium", defaultFlag: false, note: "Common in normal cert management; sensitive when an attacker-supplied cert enables TLS interception or serving content under a trusted name." },
  "DeleteBackupPlan": { service: "backup", category: "impact", severity: "high", defaultFlag: true, note: "Halting future backups degrades recoverability ahead of a destructive/ransomware attack." },
  "DeleteBackupVault": { service: "backup", category: "impact", severity: "high", defaultFlag: true, note: "Wipes stored recovery points wholesale; anti-recovery hallmark." },
  "DeleteRecoveryPoint": { service: "backup", category: "impact", severity: "high", defaultFlag: true, note: "Destroying recovery points removes restore capability; classic ransomware/anti-recovery move." },
  "PutBackupVaultAccessPolicy": { service: "backup", category: "exfiltration", severity: "medium", defaultFlag: true, note: "A permissive vault policy can grant an external account rights to restore/copy backup data." },
  "CreateComputeEnvironment": { service: "batch", category: "impact", severity: "medium", defaultFlag: false, note: "Normal for batch workloads; a favored resource-hijacking/cryptomining mechanism when unexpected." },
  "RegisterJobDefinition": { service: "batch", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when it attaches a powerful job IAM role or privileged settings to stage role abuse/container escape." },
  "CreateStack": { service: "cloudformation", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Routine IaC; sensitive when deployed with a passed service role that provisions privileged resources the caller could not create directly." },
  "CreateStackInstances": { service: "cloudformation", category: "lateral-movement", severity: "high", defaultFlag: false, note: "Normal in StackSet orgs; a powerful cross-account/region push worth review when the actor or targets are unexpected." },
  "UpdateStack": { service: "cloudformation", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Routine IaC; sensitive when the stack's execution role is abused to inject backdoors or escalate." },
  "DeleteEventDataStore": { service: "cloudtrail", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Destroys CloudTrail Lake long-retention query evidence used for investigations." },
  "DeleteTrail": { service: "cloudtrail", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Destroys the audit trail to blind detection; IaC teardown can also trigger it, but presence always warrants a look." },
  "PutEventSelectors": { service: "cloudtrail", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Narrows what management/data events are logged, letting an attacker carve out their activity while the trail stays 'on'." },
  "StopLogging": { service: "cloudtrail", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Halts CloudTrail delivery so subsequent activity is unrecorded; almost never legitimate in a monitored account." },
  "UpdateTrail": { service: "cloudtrail", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Can scope a trail to one region, break multi-region logging, or repoint delivery to a hijacked bucket." },
  "DeleteAlarms": { service: "cloudwatch", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Common in IaC/ops churn; sensitive when it removes alarms that would notify on suspicious thresholds." },
  "DisableAlarmActions": { service: "cloudwatch", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Leaves alarms in place but suppresses notifications/actions; quietly defeats alerting when abused." },
  "AdminAddUserToGroup": { service: "cognito-idp", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Routine user administration; sensitive when adding a user to a privileged group mapped to IAM roles." },
  "AdminCreateUser": { service: "cognito-idp", category: "persistence", severity: "medium", defaultFlag: false, note: "Normal app onboarding; sensitive as a foothold identity for application access." },
  "AdminSetUserPassword": { service: "cognito-idp", category: "credential-access", severity: "medium", defaultFlag: false, note: "Legitimate admin password resets occur; enables takeover of any Cognito account when abused." },
  "SetUserPoolMfaConfig": { service: "cognito-idp", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Weakening or disabling MFA on a user pool strips a key auth control for all its users." },
  "UpdateUserPoolClient": { service: "cognito-idp", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when it changes allowed auth flows, callback URLs, or token lifetimes to enable token theft." },
  "DeleteConfigRule": { service: "config", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Occurs in normal rule management; sensitive when it removes a rule so attacker misconfigs stop flagging as non-compliant." },
  "DeleteConfigurationRecorder": { service: "config", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Permanently removes Config recording, eliminating the configuration timeline attackers evade." },
  "DeleteDeliveryChannel": { service: "config", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Breaks Config's export of snapshots/history to S3, cutting off downstream evidence delivery." },
  "StopConfigurationRecorder": { service: "config", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Stops Config from recording resource changes, blinding drift and compliance detection." },
  "DeleteLandingZone": { service: "controltower", category: "impact", severity: "medium", defaultFlag: true, note: "Tears down Control Tower governance and baseline controls for the org." },
  "DisableControl": { service: "controltower", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Removes a preventive/detective guardrail across an OU." },
  "DeleteBackup": { service: "dynamodb", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Removing backups destroys recovery points; can be anti-forensic tampering." },
  "DeleteTable": { service: "dynamodb", category: "impact", severity: "high", defaultFlag: true, note: "Immediate, irreversible destruction of a table and its data; benign in dev/IaC teardown." },
  "ExportTableToPointInTime": { service: "dynamodb", category: "exfiltration", severity: "high", defaultFlag: true, note: "Exports full table data to an S3 bucket the actor controls, bypassing table-level IAM entirely." },
  "RestoreTableFromBackup": { service: "dynamodb", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Legitimate for DR; sensitive when recreating table contents into an actor-controlled table to sidestep controls." },
  "RestoreTableToPointInTime": { service: "dynamodb", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Legitimate for DR/cloning; sensitive when restoring into a new (possibly cross-account) table the attacker can read." },
  "Scan": { service: "dynamodb", category: "data-access", severity: "medium", defaultFlag: false, note: "Extremely common full-table read (data event); consistent with bulk exfiltration only in anomalous volume or from new principals." },
  "UpdateContinuousBackups": { service: "dynamodb", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Disabling PITR removes recovery capability; enabling can set up a point-in-time export." },
  "AcceptVpcPeeringConnection": { service: "ec2", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Normal networking; sensitive when completing a cross-VPC/cross-account path for pivoting." },
  "AttachInternetGateway": { service: "ec2", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Routine VPC setup; sensitive when it exposes a previously private subnet directly to the internet." },
  "AuthorizeSecurityGroupEgress": { service: "ec2", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Very common; sensitive when it loosens outbound rules to permit C2 callbacks or data exfiltration." },
  "AuthorizeSecurityGroupIngress": { service: "ec2", category: "defense-evasion", severity: "high", defaultFlag: false, note: "Highly routine; sensitive when opening 0.0.0.0/0 on 22/3389/DB ports, exposing resources to the attacker." },
  "CopySnapshot": { service: "ec2", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Legitimate for backups/migration; sensitive when copying cross-region/account to stage data outside monitored boundaries." },
  "CreateImage": { service: "ec2", category: "data-access", severity: "medium", defaultFlag: false, note: "Normal AMI baking; captures a full disk image including embedded secrets, ready for sharing/exfil." },
  "CreateKeyPair": { service: "ec2", category: "persistence", severity: "medium", defaultFlag: false, note: "Routine; sensitive when baked into launches for durable instance access." },
  "CreateNetworkAclEntry": { service: "ec2", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Normal networking; sensitive when a subnet-level rule broadly allows traffic and weakens segmentation." },
  "CreateRoute": { service: "ec2", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Routine; sensitive when a route redirects traffic through an attacker instance or opens an exfil path." },
  "CreateSnapshot": { service: "ec2", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Very common backup step; the first link of the snapshot-share-copy data-theft chain when paired with sharing." },
  "CreateTrafficMirrorSession": { service: "ec2", category: "credential-access", severity: "high", defaultFlag: true, note: "Mirrors VPC traffic to capture in-transit credentials, tokens, and sensitive data; rarely legitimate." },
  "CreateTrafficMirrorTarget": { service: "ec2", category: "exfiltration", severity: "medium", defaultFlag: true, note: "Defines the (often attacker-controlled) destination that mirrored packet captures are sent to." },
  "CreateTransitGatewayVpcAttachment": { service: "ec2", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Normal in hub-spoke networks; sensitive when bridging into networks spanning many accounts." },
  "CreateVpcPeeringConnection": { service: "ec2", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Routine; sensitive when peering to an attacker-controlled VPC/account to bridge networks." },
  "DeleteFlowLogs": { service: "ec2", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Deletes VPC Flow Logs, an anti-forensic move that blinds network-level telemetry for lateral movement/exfil." },
  "DeleteNetworkAclEntry": { service: "ec2", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when removing a NACL deny rule that was blocking traffic." },
  "DisableEbsEncryptionByDefault": { service: "ec2", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Turns off default EBS encryption, weakening data-at-rest protection for new volumes; rarely legitimate." },
  "GetPasswordData": { service: "ec2", category: "credential-access", severity: "medium", defaultFlag: false, note: "Sometimes used legitimately; retrieves the encrypted Windows Administrator password, decryptable with the key pair." },
  "ImportKeyPair": { service: "ec2", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when importing an attacker-controlled public key for persistent instance access." },
  "ModifyImageAttribute": { service: "ec2", category: "exfiltration", severity: "high", defaultFlag: false, note: "Cross-account AMI sharing happens in orgs; sensitive when sharing an AMI externally or making it public via launchPermission." },
  "ModifyInstanceAttribute": { service: "ec2", category: "privilege-escalation", severity: "high", defaultFlag: false, note: "Occurs in normal ops; sensitive when editing userData to plant a root script, disabling source/dest check, or swapping the instance profile." },
  "ModifyNetworkInterfaceAttribute": { service: "ec2", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when it changes an ENI's security groups or disables source/dest check to enable routing/pivoting." },
  "ModifySnapshotAttribute": { service: "ec2", category: "exfiltration", severity: "high", defaultFlag: false, note: "Cross-account snapshot sharing occurs legitimately; a classic volume-data exfil path when createVolumePermission is added for an external account or 'all'." },
  "ReplaceRoute": { service: "ec2", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Sensitive when rewriting a route to hijack/MITM traffic via an attacker-controlled next hop." },
  "RunInstances": { service: "ec2", category: "impact", severity: "medium", defaultFlag: false, note: "Highly routine; cryptomining/attacker-infra signal, and can escalate via an attached instance profile (iam:PassRole)." },
  "SharedSnapshotCopyInitiated": { service: "ec2", category: "exfiltration", severity: "high", defaultFlag: true, note: "Fires in the owning account when an external account copies your shared snapshot, evidencing active data theft." },
  "SharedSnapshotVolumeCreated": { service: "ec2", category: "exfiltration", severity: "high", defaultFlag: true, note: "External account created a volume from your shared snapshot, confirming access to your disk data." },
  "TerminateInstances": { service: "ec2", category: "impact", severity: "medium", defaultFlag: false, note: "Common in autoscaling/ops; sensitive as outage-causing sabotage or anti-forensic removal of a compromised host." },
  "PutImage": { service: "ecr", category: "persistence", severity: "high", defaultFlag: false, note: "Constant in CI/CD; sensitive when re-tagging a trusted tag (e.g. :latest) so downstream deployments pull backdoored images." },
  "SetRepositoryPolicy": { service: "ecr", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when granting cross-account pull/push, exposing private images." },
  "CreateService": { service: "ecs", category: "persistence", severity: "medium", defaultFlag: false, note: "Routine deployment; sensitive as self-healing persistence keeping a malicious container alive." },
  "ExecuteCommand": { service: "ecs", category: "lateral-movement", severity: "high", defaultFlag: true, note: "ECS Exec opens an interactive shell into a running container (hands-on-keyboard access)." },
  "RegisterTaskDefinition": { service: "ecs", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Routine; sensitive when specifying a powerful task role, privileged mode, or host mounts to set up role theft/container escape." },
  "RunTask": { service: "ecs", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Normal workload launch; paired with a crafted task definition it exposes task-role credentials." },
  "UpdateService": { service: "ecs", category: "persistence", severity: "medium", defaultFlag: false, note: "Routine redeploy; sensitive when pointing a trusted service at a malicious task definition." },
  "CreateAccessPoint": { service: "efs", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive as an additional application-level entry path into file system data." },
  "CreateMountTarget": { service: "efs", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Sensitive when exposing an EFS file system to another subnet reachable by attacker hosts." },
  "PutFileSystemPolicy": { service: "efs", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when granting cross-account or overly broad mount access to file data." },
  "AssociateAccessPolicy": { service: "eks", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Grants a Kubernetes RBAC policy (e.g. cluster-admin) to an IAM principal, a direct path to cluster takeover." },
  "CreateAccessEntry": { service: "eks", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Maps an arbitrary IAM principal into the cluster's access model, prerequisite for granting attacker identities Kubernetes access." },
  "CreateCluster": { service: "eks", category: "impact", severity: "medium", defaultFlag: false, note: "Legitimate provisioning; a resource-hijacking/cryptomining signal when not routine." },
  "UpdateClusterConfig": { service: "eks", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when disabling control-plane audit logging or opening the API server's public endpoint." },
  "DeleteRule": { service: "events", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Heavy benign use; sensitive when removing automated detection/response wiring." },
  "PutPermission": { service: "events", category: "lateral-movement", severity: "medium", defaultFlag: true, note: "Opens an event bus to another account, enabling cross-account event injection or exfiltration." },
  "PutRule": { service: "events", category: "persistence", severity: "medium", defaultFlag: false, note: "Common serverless wiring; a scheduled/API-event rule is a frequent persistence/trigger mechanism." },
  "PutTargets": { service: "events", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when attaching a Lambda/other target to wire up an event-driven persistence payload." },
  "CreateFilter": { service: "guardduty", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Legitimate tuning exists; sensitive when a suppression filter with auto-archive silently hides the attacker's own findings." },
  "CreateIPSet": { service: "guardduty", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when a trusted-IP list whitelists attacker infrastructure so GuardDuty stops flagging it." },
  "DeleteDetector": { service: "guardduty", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Deletes the GuardDuty detector, fully disabling threat detection for the account/region." },
  "DeletePublishingDestination": { service: "guardduty", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Removes export of findings to S3/SIEM, cutting central visibility while the detector appears healthy." },
  "DisassociateMembers": { service: "guardduty", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when a delegated admin detaches member accounts from centralized GuardDuty monitoring." },
  "UpdateDetector": { service: "guardduty", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Can suspend GuardDuty or slow finding publishing; presence warrants confirming it is benign tuning vs disabling." },
  "AddClientIDToOpenIDConnectProvider": { service: "iam", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when adding an audience that widens who can federate into roles." },
  "AddRoleToInstanceProfile": { service: "iam", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Routine for EC2 provisioning; enables EC2 credential abuse and lateral movement when abused." },
  "AddUserToGroup": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: false, note: "Common user admin; sensitive when adding a user to a privileged group to inherit its permissions." },
  "AttachGroupPolicy": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Attaches a managed policy to a group, elevating every member at once." },
  "AttachRolePolicy": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Attaches a managed policy (e.g. AdministratorAccess) to a role, broadening effective permissions." },
  "AttachUserPolicy": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Attaches a managed policy directly to a user; classic privilege escalation." },
  "ChangePassword": { service: "iam", category: "credential-access", severity: "medium", defaultFlag: false, note: "Routine hygiene; can lock out the legitimate owner post-compromise." },
  "CreateAccessKey": { service: "iam", category: "credential-access", severity: "high", defaultFlag: true, note: "Mints long-lived programmatic credentials; a top attacker action, especially when created on another principal." },
  "CreateLoginProfile": { service: "iam", category: "persistence", severity: "high", defaultFlag: true, note: "Adds console password access to a principal that had none (often programmatic-only), a classic backdoor." },
  "CreateOpenIDConnectProvider": { service: "iam", category: "persistence", severity: "high", defaultFlag: true, note: "Registers an OIDC IdP; a federated backdoor into the account if attacker-controlled." },
  "CreatePolicy": { service: "iam", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Common in policy management; sensitive when staging a permissive policy for later broad attachment." },
  "CreatePolicyVersion": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: false, note: "Frequent in IaC policy updates; sensitive when a new default version silently widens a managed policy's permissions." },
  "CreateRole": { service: "iam", category: "persistence", severity: "medium", defaultFlag: false, note: "Routine; sensitive when created with a permissive trust policy for later assumption." },
  "CreateSAMLProvider": { service: "iam", category: "persistence", severity: "high", defaultFlag: true, note: "Registers a SAML IdP; a rogue provider becomes a federated backdoor into the account." },
  "CreateServiceSpecificCredential": { service: "iam", category: "persistence", severity: "medium", defaultFlag: true, note: "Mints service-specific credentials (e.g. CodeCommit) as a stealthy secondary credential; uncommon enough to review." },
  "CreateUser": { service: "iam", category: "persistence", severity: "medium", defaultFlag: false, note: "IaC/legacy IAM use is common; a new principal is a classic backdoor identity, especially in SSO-first orgs, so correlate with who created it." },
  "CreateVirtualMFADevice": { service: "iam", category: "persistence", severity: "medium", defaultFlag: false, note: "Normal user/root onboarding; can be attacker persistence binding their own device on a compromised identity." },
  "DeactivateMFADevice": { service: "iam", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Removes MFA from a user, weakening authentication to enable takeover; rarely part of routine ops." },
  "DeleteAccountPasswordPolicy": { service: "iam", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Removes the password policy entirely, lowering credential hygiene account-wide; rarely legitimate." },
  "DeleteLoginProfile": { service: "iam", category: "impact", severity: "medium", defaultFlag: false, note: "Can be cleanup or a deliberate lockout of a user, or covering tracks after abuse." },
  "DeleteRole": { service: "iam", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Routine teardown; can destroy evidence of a backdoor trust relationship." },
  "DeleteRolePermissionsBoundary": { service: "iam", category: "privilege-escalation", severity: "medium", defaultFlag: true, note: "Removes a role's permissions boundary, uncapping its effective permissions; uncommon and security-relevant." },
  "DeleteUser": { service: "iam", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Routine offboarding; can destroy evidence of a rogue identity." },
  "DeleteUserPermissionsBoundary": { service: "iam", category: "privilege-escalation", severity: "medium", defaultFlag: true, note: "Removes a user's permissions boundary, uncapping their effective permissions; uncommon and security-relevant." },
  "DeleteVirtualMFADevice": { service: "iam", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Occurs during legitimate device rotation; can strip an auth protection ahead of takeover." },
  "EnableMFADevice": { service: "iam", category: "persistence", severity: "medium", defaultFlag: false, note: "Normal account hardening; an attacker registering their own device locks in access, so correlate who/when." },
  "GetAccountAuthorizationDetails": { service: "iam", category: "discovery", severity: "high", defaultFlag: false, note: "Generated by audit/compliance tooling; a prime enumeration signal that dumps the entire IAM config in one call from an unexpected principal." },
  "PutGroupPolicy": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Inlines an arbitrary permissions policy onto a group, elevating all members." },
  "PutRolePolicy": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Inlines an arbitrary permissions policy onto a role." },
  "PutUserPermissionsBoundary": { service: "iam", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Can add an intended guardrail (benign) or relax one; sensitive when it removes an intended ceiling." },
  "PutUserPolicy": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Inlines an arbitrary permissions policy onto a user." },
  "SetDefaultPolicyVersion": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: false, note: "Occurs in IaC policy updates; a stealthy privesc when switching to a pre-staged permissive version." },
  "SimulatePrincipalPolicy": { service: "iam", category: "discovery", severity: "medium", defaultFlag: false, note: "Sensitive when used to hunt for privilege-escalation paths by testing a principal's effective permissions." },
  "UpdateAccountPasswordPolicy": { service: "iam", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Can strengthen or weaken; sensitive when it weakens length/rotation to ease credential attacks." },
  "UpdateAssumeRolePolicy": { service: "iam", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Rewrites a role's trust policy to let an attacker-controlled principal assume it." },
  "UpdateLoginProfile": { service: "iam", category: "credential-access", severity: "high", defaultFlag: true, note: "Resets a user's console password; a classic account-takeover step, especially when target differs from the caller." },
  "UpdateOpenIDConnectProviderThumbprint": { service: "iam", category: "persistence", severity: "medium", defaultFlag: false, note: "Legitimate on cert rotation; sensitive when changed to trust a rogue IdP certificate." },
  "UpdateSAMLProvider": { service: "iam", category: "persistence", severity: "high", defaultFlag: true, note: "Alters a SAML IdP's metadata, potentially trusting an attacker-controlled identity provider." },
  "UploadSigningCertificate": { service: "iam", category: "persistence", severity: "medium", defaultFlag: true, note: "Uploads an X.509 signing certificate as an alternate API credential; uncommon and credential-adding." },
  "CreateGroupMembership": { service: "identitystore", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when adding a user to a privileged Identity Center group that inherits permission-set assignments." },
  "Disable": { service: "inspector2", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Disables Amazon Inspector vulnerability scanning; the generic name makes eventSource=inspector2 essential context." },
  "CreateGrant": { service: "kms", category: "privilege-escalation", severity: "high", defaultFlag: false, note: "Very common from AWS service integrations (EBS, etc.); a stealthy persistent-decrypt grant when the grantee is an unexpected principal." },
  "Decrypt": { service: "kms", category: "credential-access", severity: "medium", defaultFlag: false, note: "Core action for reading protected secrets/envelope-encrypted data; anomalous volume or new principals matter, otherwise pure noise." },
  "DisableKey": { service: "kms", category: "impact", severity: "high", defaultFlag: true, note: "Instantly denies decryption across every resource encrypted with the key; a fast DoS/ransom lever." },
  "DisableKeyRotation": { service: "kms", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Weakens crypto hygiene and can preserve a compromised key version an attacker still controls." },
  "ImportKeyMaterial": { service: "kms", category: "persistence", severity: "medium", defaultFlag: false, note: "Legitimate for BYOK; gives an attacker offline control over what the CMK can decrypt when unexpected." },
  "PutKeyPolicy": { service: "kms", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Rewrites who can use/administer a key, letting an attacker grant themselves decrypt rights or lock out owners." },
  "ScheduleKeyDeletion": { service: "kms", category: "impact", severity: "high", defaultFlag: true, note: "Queues irreversible destruction of a CMK, rendering all data it protects permanently unrecoverable after the window." },
  "AddLayerVersionPermission": { service: "lambda", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when sharing a layer cross-account as a supply-chain path to distribute a malicious layer." },
  "AddPermission": { service: "lambda", category: "persistence", severity: "high", defaultFlag: false, note: "Fires routinely for S3/EventBridge triggers; sensitive when granting invoke to a public or cross-account principal." },
  "CreateEventSourceMapping": { service: "lambda", category: "persistence", severity: "medium", defaultFlag: false, note: "Normal wiring; gives event-driven persistence or a covert tap on a stream/queue/table when abused." },
  "CreateFunction": { service: "lambda", category: "persistence", severity: "medium", defaultFlag: false, note: "Routine; a function attached to an IAM execution role is a common foothold for running attacker code." },
  "CreateFunctionUrlConfig": { service: "lambda", category: "persistence", severity: "high", defaultFlag: false, note: "Legitimate for webhooks; sensitive when AuthType=NONE exposes an unauthenticated internet-facing backdoor to the code." },
  "UpdateFunctionCode": { service: "lambda", category: "persistence", severity: "high", defaultFlag: false, note: "Constant in CI/CD; the classic Lambda backdoor/supply-chain tampering vector when overwriting a trusted, privileged function." },
  "UpdateFunctionConfiguration": { service: "lambda", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when swapping the execution role or injecting env vars/layers to escalate or alter behavior." },
  "DeleteLogGroup": { service: "logs", category: "defense-evasion", severity: "high", defaultFlag: false, note: "Common in IaC teardown; anti-forensic when destroying application/VPC/Lambda logs and attached metric filters." },
  "DeleteLogStream": { service: "logs", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when erasing evidence of activity while leaving the log group intact." },
  "DeleteMetricFilter": { service: "logs", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when deleting the metric filter feeding alarms (e.g. root-login/unauthorized-API), breaking log-based detections." },
  "DeleteSubscriptionFilter": { service: "logs", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when it stops real-time log forwarding to a SIEM/Lambda/Firehose." },
  "PutRetentionPolicy": { service: "logs", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Routine config; sensitive when shortening retention (e.g. to one day) to prune logs before investigators can pull them." },
  "DisableMacie": { service: "macie2", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Disables Macie, ending sensitive-data discovery that could reveal exfiltration staging." },
  "UpdateMacieSession": { service: "macie2", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when suspending the session or cutting finding-publishing frequency to degrade data-security visibility." },
  "AcceptHandshake": { service: "organizations", category: "persistence", severity: "medium", defaultFlag: false, note: "Normal org onboarding; sensitive when completing an invite that joins a malicious account or enables org takeover." },
  "AttachPolicy": { service: "organizations", category: "defense-evasion", severity: "high", defaultFlag: false, note: "Can be a benign guardrail addition or a permissive SCP that grants broad allow / overrides restrictive policy across accounts." },
  "CloseAccount": { service: "organizations", category: "impact", severity: "medium", defaultFlag: true, note: "Closing a member account is destructive and can disrupt services or hide prior activity; rarely routine." },
  "CreateAccount": { service: "organizations", category: "persistence", severity: "medium", defaultFlag: false, note: "Normal provisioning; a new member account can serve as an attacker foothold under the org's trust." },
  "DeletePolicy": { service: "organizations", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Deletes an SCP, removing a guardrail definition entirely from the org." },
  "DeregisterDelegatedAdministrator": { service: "organizations", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Removing delegated admin for GuardDuty/Security Hub/Access Analyzer can blind org-wide detection." },
  "DetachPolicy": { service: "organizations", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Detaching an SCP strips org-wide guardrails from an account or OU, re-enabling denied actions." },
  "DisableAWSServiceAccess": { service: "organizations", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Disabling trusted access can sever a security service's org-wide integration; uncommon and high-impact." },
  "DisablePolicyType": { service: "organizations", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Disabling SERVICE_CONTROL_POLICY turns off all SCP enforcement for the org root at once." },
  "EnableAWSServiceAccess": { service: "organizations", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when enabling trusted access wires in attacker tooling org-wide." },
  "InviteAccountToOrganization": { service: "organizations", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when inviting an attacker-controlled account extends org trust and RAM/SSO reach to it." },
  "LeaveOrganization": { service: "organizations", category: "defense-evasion", severity: "high", defaultFlag: true, note: "A member leaving the org drops all SCPs, delegated security services, and consolidated logging in one call." },
  "MoveAccount": { service: "organizations", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Routine reorganization; sensitive when relocating an account to a less-restricted OU to escape SCPs." },
  "RegisterDelegatedAdministrator": { service: "organizations", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Registers a member account as delegated admin for an org service, granting cross-account control." },
  "RemoveAccountFromOrganization": { service: "organizations", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Ejecting a member from the management side removes it from org guardrails and centralized monitoring." },
  "UpdatePolicy": { service: "organizations", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Editing an SCP document can silently weaken deny statements protecting the whole org." },
  "AcceptResourceShareInvitation": { service: "ram", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Sensitive when pulling external shared resources into the account to enable pivots." },
  "AssociateResourceShare": { service: "ram", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Sensitive when adding external principals/resources extends access outside the account boundary." },
  "CreateResourceShare": { service: "ram", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Sensitive when sharing resources to an external account enables cross-account access or data exposure." },
  "AddRoleToDBCluster": { service: "rds", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Enables Aurora S3 import/export; sensitive as a data-movement path out of the database." },
  "AddRoleToDBInstance": { service: "rds", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Associates an IAM role to enable S3/other integrations usable for exfiltration." },
  "CopyDBClusterSnapshot": { service: "rds", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Legitimate for backups; sensitive when copied cross-region/account as an exfil staging step." },
  "CopyDBSnapshot": { service: "rds", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Legitimate for backups; sensitive when staging data cross-region/account outside monitoring scope." },
  "CreateDBClusterSnapshot": { service: "rds", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Manual cluster snapshot commonly precedes an attribute-share or copy used to move data out." },
  "CreateDBSnapshot": { service: "rds", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Benign on its own; the first link in the sharing/export exfil chain." },
  "DeleteDBCluster": { service: "rds", category: "impact", severity: "high", defaultFlag: true, note: "Can wipe an entire Aurora/DocDB/Neptune dataset, especially with SkipFinalSnapshot." },
  "DeleteDBInstance": { service: "rds", category: "impact", severity: "high", defaultFlag: true, note: "Destructive removal, especially with SkipFinalSnapshot, causes irreversible data loss." },
  "DeleteDBSnapshot": { service: "rds", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when destroying recovery points as anti-forensic tampering to block restoration." },
  "DownloadDBLogFilePortion": { service: "rds", category: "data-access", severity: "medium", defaultFlag: false, note: "Sensitive when DB logs leak query text, error data, or embedded credentials." },
  "ModifyDBCluster": { service: "rds", category: "credential-access", severity: "high", defaultFlag: false, note: "Noisy config event; inspect params: MasterUserPassword reset hands over admin DB credentials, PubliclyAccessible exposes it." },
  "ModifyDBClusterSnapshotAttribute": { service: "rds", category: "exfiltration", severity: "high", defaultFlag: true, note: "Shares an Aurora/Neptune/DocumentDB cluster snapshot to another account; rarely benign and a strong exfil signal." },
  "ModifyDBInstance": { service: "rds", category: "credential-access", severity: "high", defaultFlag: false, note: "Noisy config event; inspect params: MasterUserPassword reset grants DB access, PubliclyAccessible exposes it to the internet." },
  "ModifyDBSnapshotAttribute": { service: "rds", category: "exfiltration", severity: "high", defaultFlag: true, note: "Sharing a snapshot with an external or all accounts is the classic RDS cross-account data-exfiltration move." },
  "RestoreDBClusterFromSnapshot": { service: "rds", category: "exfiltration", severity: "high", defaultFlag: false, note: "Legitimate for DR/cloning; sensitive when restoring into attacker-controlled infrastructure for data theft." },
  "RestoreDBClusterToPointInTime": { service: "rds", category: "exfiltration", severity: "high", defaultFlag: false, note: "Legitimate for DR; sensitive when a PITR clone recreates current data in a cluster the attacker can expose/query." },
  "RestoreDBInstanceFromDBSnapshot": { service: "rds", category: "exfiltration", severity: "high", defaultFlag: false, note: "Legitimate for DR; sensitive when restored into an instance the actor controls to read data without touching the original." },
  "RestoreDBInstanceToPointInTime": { service: "rds", category: "exfiltration", severity: "high", defaultFlag: false, note: "Legitimate for DR; sensitive when a PITR restore clones a live DB into a new instance, bypassing source access controls." },
  "StartExportTask": { service: "rds", category: "exfiltration", severity: "high", defaultFlag: true, note: "Exports an RDS snapshot as Parquet to an S3 bucket the actor can read, bypassing DB engine controls." },
  "AuthorizeSnapshotAccess": { service: "redshift", category: "exfiltration", severity: "high", defaultFlag: true, note: "Grants another AWS account access to a Redshift snapshot; the classic cross-account warehouse exfil technique." },
  "CreateClusterSnapshot": { service: "redshift", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Manual snapshot precedes AuthorizeSnapshotAccess or copy in the warehouse-exfil chain." },
  "DeleteCluster": { service: "redshift", category: "impact", severity: "high", defaultFlag: true, note: "Warehouse deletion, especially skipping the final snapshot, is destructive and irreversible." },
  "EnableSnapshotCopy": { service: "redshift", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Sensitive when enabling automatic cross-region snapshot copy to move data to a region outside monitoring." },
  "GetClusterCredentials": { service: "redshift", category: "credential-access", severity: "medium", defaultFlag: false, note: "Used in normal auth flows; abused to mint temporary DB credentials for unauthorized warehouse access." },
  "ModifyCluster": { service: "redshift", category: "credential-access", severity: "high", defaultFlag: false, note: "Inspect params: MasterUserPassword reset yields admin access and PubliclyAccessible exposes the warehouse publicly." },
  "ModifyClusterIamRoles": { service: "redshift", category: "privilege-escalation", severity: "high", defaultFlag: false, note: "Done legitimately for integrations; attaching IAM roles enables UNLOAD/COPY to arbitrary S3, a direct exfil path." },
  "RestoreFromClusterSnapshot": { service: "redshift", category: "exfiltration", severity: "high", defaultFlag: false, note: "Legitimate for DR; sensitive when restoring into an attacker-controlled cluster to read warehouse data." },
  "ChangeResourceRecordSets": { service: "route53", category: "impact", severity: "medium", defaultFlag: false, note: "Extremely routine; enables subdomain takeover, traffic redirection, and ACME-based cert issuance when abused." },
  "DeleteHostedZone": { service: "route53", category: "impact", severity: "medium", defaultFlag: false, note: "Occurs in IaC teardown; can black-hole all resolution for the associated domains." },
  "DisableDomainTransferLock": { service: "route53domains", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Removing the registrar transfer lock is a classic precursor step to stealing a domain." },
  "TransferDomainToAnotherAwsAccount": { service: "route53domains", category: "exfiltration", severity: "high", defaultFlag: true, note: "Moves domain control to an attacker-owned account; a rare, near-irreversible hijack of the org's namespace." },
  "UpdateDomainNameservers": { service: "route53domains", category: "impact", severity: "high", defaultFlag: true, note: "Repointing nameservers hands full DNS resolution to attacker infrastructure, enabling traffic and email hijack." },
  "CopyObject": { service: "s3", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Common data movement; server-side copy can move data into an attacker-controlled bucket without a client download." },
  "DeleteBucket": { service: "s3", category: "impact", severity: "high", defaultFlag: true, note: "Bucket deletion is destructive and irreversible, a hallmark of sabotage/anti-forensics; benign in IaC teardown." },
  "DeleteBucketEncryption": { service: "s3", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Removing default encryption weakens data-at-rest protection and can precede exfiltration/tampering; rarely legitimate." },
  "DeleteBucketPolicy": { service: "s3", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when removing a restrictive policy strips deny rules and opens data that was locked down." },
  "DeleteBucketPublicAccessBlock": { service: "s3", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Deleting the public access block is rarely legitimate and directly enables public data exposure." },
  "DeleteObjects": { service: "s3", category: "impact", severity: "medium", defaultFlag: false, note: "Routine cleanup; bulk deletion consistent with sabotage or ransomware cleanup." },
  "PutAccessPointPolicy": { service: "s3", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when an access point policy grants cross-account or overly broad access as an alternate path to bucket data." },
  "PutBucketAcl": { service: "s3", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Adding AllUsers/AuthenticatedUsers or a foreign canonical ID to a bucket ACL exposes data broadly." },
  "PutBucketEncryption": { service: "s3", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when changing default encryption to an attacker KMS key or weaker setting to undermine confidentiality." },
  "PutBucketLifecycle": { service: "s3", category: "impact", severity: "medium", defaultFlag: false, note: "Sensitive when aggressive expiration rules destroy objects or purge logs for anti-forensics." },
  "PutBucketLogging": { service: "s3", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Routine config; sensitive when overwriting the target to disable S3 access logging and hide object access." },
  "PutBucketPolicy": { service: "s3", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Rewriting a bucket policy can grant public or attacker-owned cross-account access to all objects." },
  "PutBucketPublicAccessBlock": { service: "s3", category: "defense-evasion", severity: "high", defaultFlag: false, note: "Can strengthen (enable) or relax the block; sensitive when relaxing/disabling removes the guardrail against public exposure." },
  "PutBucketReplication": { service: "s3", category: "exfiltration", severity: "high", defaultFlag: false, note: "Legitimate replication exists; sensitive when rules silently and continuously copy every object to an external/attacker cross-account bucket." },
  "PutBucketVersioning": { service: "s3", category: "impact", severity: "medium", defaultFlag: false, note: "Sensitive when suspending versioning removes recovery of overwritten objects; a common ransomware precursor." },
  "PutBucketWebsite": { service: "s3", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Sensitive when static website hosting turns a private bucket into a publicly reachable data/malware endpoint." },
  "PutObjectAcl": { service: "s3", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when object-level ACLs make individual sensitive objects public without touching the bucket policy." },
  "PutObjectLockConfiguration": { service: "s3", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Weakening or disabling object lock removes immutability protections that block deletion and ransomware." },
  "BatchGetSecretValue": { service: "secretsmanager", category: "credential-access", severity: "high", defaultFlag: true, note: "Bulk retrieval API that harvests many secrets in one call; a strong exfiltration indicator rarely seen in normal ops." },
  "DeleteSecret": { service: "secretsmanager", category: "impact", severity: "medium", defaultFlag: false, note: "Sensitive when destroying a secret breaks dependent services or covers tracks after theft." },
  "GetSecretValue": { service: "secretsmanager", category: "credential-access", severity: "high", defaultFlag: false, note: "Primary secret-theft signal but also routine app access; watch new principals, mass pulls, or secrets outside a role's normal scope." },
  "ListSecrets": { service: "secretsmanager", category: "discovery", severity: "medium", defaultFlag: false, note: "Enumerates secret names/ARNs; the recon step before targeted GetSecretValue theft." },
  "PutResourcePolicy": { service: "secretsmanager", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Attaches a resource policy that can grant cross-account or public read access to a secret's value." },
  "PutSecretValue": { service: "secretsmanager", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when overwriting a secret with backdoored credentials or tampering that survives across sessions." },
  "ReplicateSecretToRegions": { service: "secretsmanager", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Sensitive when copying a secret into attacker-chosen regions as a stealthy staging/exfil path outside normal monitoring." },
  "BatchDisableStandards": { service: "securityhub", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when disabling entire compliance standards (CIS/FSBP) silences broad swaths of control failures at once." },
  "DisableSecurityHub": { service: "securityhub", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Turns off Security Hub, disabling aggregated findings and standards checks for the account." },
  "PutIdentityPolicy": { service: "ses", category: "privilege-escalation", severity: "medium", defaultFlag: true, note: "Attaches a policy to a sending identity that can authorize cross-account or external principals to send as that identity." },
  "UpdateAccountSendingEnabled": { service: "ses", category: "impact", severity: "medium", defaultFlag: true, note: "Re-enabling account sending (often after suppression) is typically done to resume bulk spam or phishing." },
  "VerifyDomainIdentity": { service: "ses", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when verifying a new sending domain stands up phishing/spam infrastructure from a trusted account." },
  "VerifyEmailIdentity": { service: "ses", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when verifying a new sender identity to abuse the account's email-sending reputation." },
  "DeleteProtection": { service: "shield", category: "defense-evasion", severity: "medium", defaultFlag: true, note: "Removing Shield Advanced protection strips DDoS mitigation from a resource; rarely legitimate." },
  "ConsoleLogin": { service: "signin", category: "initial-access", severity: "high", defaultFlag: true, note: "Primary interactive entry point; check responseElements for Failure, additionalEventData.MFAUsed=No, and userIdentity.type=Root for brute force, MFA-less logins, and root usage." },
  "PasswordRecoveryCompleted": { service: "signin", category: "credential-access", severity: "high", defaultFlag: true, note: "A password reset actually succeeded, meaning control of the account's credentials may have changed hands." },
  "PasswordRecoveryRequested": { service: "signin", category: "credential-access", severity: "high", defaultFlag: true, note: "Account-takeover precursor: someone initiated a password reset (often against the root email); verify it was the legitimate owner." },
  "SwitchRole": { service: "signin", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Routine daily workflow in many orgs; sensitive when pivoting into higher-privilege or cross-account roles." },
  "SetTopicAttributes": { service: "sns", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when rewriting a topic's access policy grants external accounts publish/subscribe rights." },
  "Subscribe": { service: "sns", category: "exfiltration", severity: "medium", defaultFlag: false, note: "Very common legitimately; sensitive when subscribing an attacker-controlled endpoint (email/HTTP/SQS) silently exfiltrates notifications." },
  "CreateActivation": { service: "ssm", category: "persistence", severity: "medium", defaultFlag: true, note: "Registers hybrid activation credentials that let attacker-controlled machines join as managed instances for durable access." },
  "CreateDocument": { service: "ssm", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when a malicious SSM document becomes a reusable execution backdoor on instances." },
  "GetParameter": { service: "ssm", category: "credential-access", severity: "medium", defaultFlag: false, note: "Routine app config reads; SecureString parameters often hold credentials, so reads by unusual principals/targets warrant review." },
  "GetParameters": { service: "ssm", category: "credential-access", severity: "medium", defaultFlag: false, note: "Batch fetch including SecureStrings; useful for harvesting secrets when from unexpected principals." },
  "GetParametersByPath": { service: "ssm", category: "credential-access", severity: "medium", defaultFlag: false, note: "Used legitimately by apps; a strong bulk-secret-harvesting/recon signal when recursively dumping a parameter tree from an unusual principal." },
  "ModifyDocumentPermission": { service: "ssm", category: "privilege-escalation", severity: "medium", defaultFlag: true, note: "Shares a document with other accounts or publicly, exposing it or granting outside principals execution rights." },
  "PutParameter": { service: "ssm", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when writing/overwriting parameters that instances and pipelines consume enables backdoored config/credentials." },
  "SendCommand": { service: "ssm", category: "lateral-movement", severity: "high", defaultFlag: false, note: "Heavy legitimate use for patching/ops; a direct control-plane-to-host RCE path when from an unusual principal or against unexpected targets." },
  "StartAutomationExecution": { service: "ssm", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when automation documents run under an assume role abused to execute actions with elevated permissions." },
  "StartSession": { service: "ssm", category: "lateral-movement", severity: "high", defaultFlag: false, note: "Common as primary admin access in SSM-first orgs; opens an interactive shell into an instance, bypassing SSH/network controls, so watch unusual principals." },
  "UpdateDocument": { service: "ssm", category: "persistence", severity: "medium", defaultFlag: false, note: "Sensitive when modifying an executed document injects commands into trusted automation." },
  "AttachCustomerManagedPolicyReferenceToPermissionSet": { service: "sso", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when referencing a customer-managed policy that expands a permission set's effective access." },
  "AttachManagedPolicyToPermissionSet": { service: "sso", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Attaching AdministratorAccess or similar to a permission set grants broad rights to all its assignees across accounts." },
  "CreateAccountAssignment": { service: "sso", category: "privilege-escalation", severity: "high", defaultFlag: false, note: "Routine access administration; sensitive when assigning a privileged permission set or to an unexpected principal in a target account." },
  "CreatePermissionSet": { service: "sso", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when a new permission set defines elevated access to be provisioned across accounts." },
  "ProvisionPermissionSet": { service: "sso", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when pushing updated permission-set policies to assigned accounts applies escalated access." },
  "PutInlinePolicyToPermissionSet": { service: "sso", category: "privilege-escalation", severity: "high", defaultFlag: true, note: "Adding an inline admin policy to a permission set escalates access across every account it targets." },
  "PutPermissionsBoundaryToPermissionSet": { service: "sso", category: "privilege-escalation", severity: "medium", defaultFlag: false, note: "Sensitive when altering a permission set's boundary widens or removes the ceiling on effective permissions." },
  "UpdateInstanceAccessControlAttributeConfiguration": { service: "sso", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when changing ABAC attribute config alters how Identity Center evaluates access decisions." },
  "AssumeRole": { service: "sts", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Ubiquitous role-chaining/pivot primitive; central to lateral movement but far too common to flag by default." },
  "AssumeRoleWithSAML": { service: "sts", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "Federated SAML sign-in; sensitive on an anomalous source or role." },
  "AssumeRoleWithWebIdentity": { service: "sts", category: "lateral-movement", severity: "medium", defaultFlag: false, note: "OIDC/web-identity federation (e.g. CI); abused via misconfigured trust conditions." },
  "GetFederationToken": { service: "sts", category: "credential-access", severity: "medium", defaultFlag: false, note: "Sensitive when producing federated temporary credentials to create scoped sessions that evade some controls." },
  "DeleteLoggingConfiguration": { service: "wafv2", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Removing WAF logging blinds detection of the requests the ACL would otherwise record." },
  "DeleteWebACL": { service: "wafv2", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Deleting a Web ACL removes application-layer filtering that blocks exploitation traffic." },
  "DisassociateWebACL": { service: "wafv2", category: "defense-evasion", severity: "high", defaultFlag: true, note: "Detaching a Web ACL from an ALB/API Gateway/CloudFront silently exposes the resource with the ACL still intact." },
  "UpdateWebACL": { service: "wafv2", category: "defense-evasion", severity: "medium", defaultFlag: false, note: "Sensitive when editing WAF rules to whitelist attacker IPs or disable protections while the ACL appears intact." },
};

/** Default-set membership (baseline). The app uses the user's EFFECTIVE set
 *  (api/settings.ts effectiveSensitive) instead; this is the fallback/default. */
export function isSensitive(eventName: string): boolean {
  return DEFAULT_SENSITIVE_APIS.has(eventName);
}

/** The "why this is flagged" note for a sensitive event, for hover tooltips. */
export function sensitiveNote(eventName: string): string | undefined {
  return SENSITIVE_INFO[eventName]?.note;
}
