// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {awsflow} from '../models';
import {model} from '../models';
import {store} from '../models';
import {config} from '../models';

export function ApplyCaptureFilter(arg1:string):Promise<void>;

export function CheckTrail(arg1:string,arg2:string):Promise<awsflow.TrailStatus>;

export function ClearEvents():Promise<void>;

export function ExportEventsJSON(arg1:string):Promise<string>;

export function GetEventRaw(arg1:number):Promise<string>;

export function GetInitialEvents():Promise<Array<model.CloudTrailEvent>>;

export function IngestFile(arg1:string):Promise<number>;

export function IngestText(arg1:string):Promise<number>;

export function ListProfiles():Promise<Array<awsflow.Profile>>;

export function LoadDumpPath(arg1:string):Promise<Array<model.CloudTrailEvent>>;

export function LoadDumpText(arg1:string):Promise<Array<model.CloudTrailEvent>>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function MaximizeWindow():Promise<void>;

export function QueryAggregates(arg1:store.Filter):Promise<store.Aggregates>;

export function QueryLineage(arg1:number):Promise<store.Lineage>;

export function QueryLineageChildren(arg1:string):Promise<store.LineageTree>;

export function QueryLineageEvents(arg1:string):Promise<store.LineageTree>;

export function QueryLineageGraph(arg1:number):Promise<store.LineageTree>;

export function QueryNewer(arg1:store.Filter,arg2:number,arg3:number):Promise<Array<store.Row>>;

export function QueryPage(arg1:store.Filter,arg2:number,arg3:number):Promise<Array<store.Row>>;

export function RawBySeqs(arg1:Array<number>):Promise<Array<string>>;

export function RequiredPermissions(arg1:string):Promise<Array<config.RequiredPermission>>;

export function RunLoginCommand(arg1:string):Promise<void>;

export function SelectDumpFile():Promise<string>;

export function SetConnection(arg1:config.ConnectionConfig):Promise<void>;

export function SigmaRun(arg1:string):Promise<store.SigmaResult>;

export function StartCapture():Promise<awsflow.Infra>;

export function StopCapture():Promise<void>;

export function TeardownCapture():Promise<void>;

export function VerifyIdentity(arg1:string,arg2:string):Promise<awsflow.Identity>;
