// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {awsflow} from '../models';
import {main} from '../models';
import {attribution} from '../models';
import {model} from '../models';
import {config} from '../models';

export function Analyze(arg1:store.AnalysisOptions,arg2:string):Promise<store.ActivityAnalysis>;

export function ApplyCaptureFilter(arg1:string):Promise<void>;

export function CancelQuery(arg1:string):Promise<void>;

export function CheckQueue(arg1:string,arg2:string):Promise<void>;

export function CheckTrail(arg1:string,arg2:string):Promise<awsflow.TrailStatus>;

export function ClearEvents():Promise<void>;

export function ExportEventsJSON(arg1:string):Promise<string>;

export function ExportFiltered(arg1:store.Filter,arg2:store.Snapshot,arg3:string):Promise<main.FilteredExport>;

export function ExportInvestigation(arg1:store.InvestigationOptions,arg2:string):Promise<main.InvestigationExport>;

export function GetAttributionSettings():Promise<attribution.Config>;

export function GetEventEvidence(arg1:number,arg2:number):Promise<store.EvidencePage>;

export function GetEventEvidenceSnapshot(arg1:number,arg2:number,arg3:store.Snapshot):Promise<store.EvidencePage>;

export function GetEventRaw(arg1:number):Promise<string>;

export function GetEvidenceSnapshot():Promise<store.Snapshot>;

export function GetInitialEvents():Promise<Array<model.CloudTrailEvent>>;

export function GetLineageAttribution(arg1:number,arg2:store.Snapshot):Promise<main.LineageAttribution>;

export function GetObservation(arg1:number):Promise<string>;

export function GetObservationSnapshot(arg1:number,arg2:store.Snapshot):Promise<string>;

export function GetRecoveryState():Promise<main.RecoveryState>;

export function Hunt(arg1:store.HuntOptions,arg2:string):Promise<store.HuntResult>;

export function IngestFile(arg1:string):Promise<number>;

export function IngestText(arg1:string):Promise<number>;

export function Investigate(arg1:store.InvestigationOptions,arg2:string):Promise<store.Investigation>;

export function ListProfiles():Promise<Array<awsflow.Profile>>;

export function LoadDumpPath(arg1:string):Promise<Array<model.CloudTrailEvent>>;

export function LoadDumpText(arg1:string):Promise<Array<model.CloudTrailEvent>>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function MaximizeWindow():Promise<void>;

export function QueryAggregates(arg1:store.Filter):Promise<store.Aggregates>;

export function QueryAggregatesRequest(arg1:store.Filter,arg2:string):Promise<store.Aggregates>;

export function QueryLineage(arg1:number):Promise<store.Lineage>;

export function QueryLineageChildren(arg1:string,arg2:store.Snapshot):Promise<store.LineageTree>;

export function QueryLineageEvents(arg1:string,arg2:store.Snapshot):Promise<store.LineageTree>;

export function QueryLineageGraph(arg1:number):Promise<store.LineageTree>;

export function QueryLineageGraphSnapshot(arg1:number,arg2:store.Snapshot):Promise<store.LineageTree>;

export function QueryLineageRaw(arg1:number,arg2:store.Snapshot):Promise<string>;

export function QueryLineageSnapshot(arg1:number,arg2:store.Snapshot):Promise<store.Lineage>;

export function QueryNewer(arg1:store.Filter,arg2:number,arg3:number):Promise<Array<store.Row>>;

export function QueryPage(arg1:store.Filter,arg2:number,arg3:number):Promise<Array<store.Row>>;

export function QuerySearch(arg1:store.Filter,arg2:string,arg3:number):Promise<store.SearchResult>;

export function QuerySnapshotPage(arg1:store.Filter,arg2:store.Snapshot,arg3:number,arg4:number):Promise<Array<store.Row>>;

export function RawBySeqs(arg1:Array<number>):Promise<Array<string>>;

export function RequiredPermissions(arg1:string):Promise<Array<config.RequiredPermission>>;

export function ResolveLineageAttribution(arg1:string,arg2:number,arg3:store.Snapshot):Promise<main.LineageAttribution>;

export function ResumeCapture():Promise<awsflow.Infra>;

export function RunLoginCommand(arg1:string):Promise<void>;

export function SaveAttributionSettings(arg1:attribution.Config):Promise<void>;

export function SelectDumpFile():Promise<string>;

export function SetConnection(arg1:config.ConnectionConfig):Promise<void>;

export function SigmaRun(arg1:string):Promise<store.SigmaResult>;

export function SigmaRunRequest(arg1:string,arg2:string):Promise<store.SigmaResult>;

export function SigmaSuite(arg1:Array<store.SigmaRuleInput>,arg2:string):Promise<store.SigmaSuiteResult>;

export function StartCapture():Promise<awsflow.Infra>;

export function StopCapture():Promise<void>;

export function TeardownCapture():Promise<void>;

export function VerifyIdentity(arg1:string,arg2:string):Promise<awsflow.Identity>;
