// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1, arg2) {
  return window['go']['main']['App']['Analyze'](arg1, arg2);
}

export function ApplyCaptureFilter(arg1) {
  return window['go']['main']['App']['ApplyCaptureFilter'](arg1);
}

export function CancelQuery(arg1) {
  return window['go']['main']['App']['CancelQuery'](arg1);
}

export function CheckQueue(arg1, arg2) {
  return window['go']['main']['App']['CheckQueue'](arg1, arg2);
}

export function CheckTrail(arg1, arg2) {
  return window['go']['main']['App']['CheckTrail'](arg1, arg2);
}

export function ClearEvents() {
  return window['go']['main']['App']['ClearEvents']();
}

export function ExportEventsJSON(arg1) {
  return window['go']['main']['App']['ExportEventsJSON'](arg1);
}

export function ExportFiltered(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportFiltered'](arg1, arg2, arg3);
}

export function ExportInvestigation(arg1, arg2) {
  return window['go']['main']['App']['ExportInvestigation'](arg1, arg2);
}

export function GetAttributionSettings() {
  return window['go']['main']['App']['GetAttributionSettings']();
}

export function GetEventEvidence(arg1, arg2) {
  return window['go']['main']['App']['GetEventEvidence'](arg1, arg2);
}

export function GetEventEvidenceSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetEventEvidenceSnapshot'](arg1, arg2, arg3);
}

export function GetEventRaw(arg1) {
  return window['go']['main']['App']['GetEventRaw'](arg1);
}

export function GetEvidenceSnapshot() {
  return window['go']['main']['App']['GetEvidenceSnapshot']();
}

export function GetInitialEvents() {
  return window['go']['main']['App']['GetInitialEvents']();
}

export function GetLineageAttribution(arg1, arg2) {
  return window['go']['main']['App']['GetLineageAttribution'](arg1, arg2);
}

export function GetObservation(arg1) {
  return window['go']['main']['App']['GetObservation'](arg1);
}

export function GetObservationSnapshot(arg1, arg2) {
  return window['go']['main']['App']['GetObservationSnapshot'](arg1, arg2);
}

export function GetRecoveryState() {
  return window['go']['main']['App']['GetRecoveryState']();
}

export function Hunt(arg1, arg2) {
  return window['go']['main']['App']['Hunt'](arg1, arg2);
}

export function IngestFile(arg1) {
  return window['go']['main']['App']['IngestFile'](arg1);
}

export function IngestText(arg1) {
  return window['go']['main']['App']['IngestText'](arg1);
}

export function Investigate(arg1, arg2) {
  return window['go']['main']['App']['Investigate'](arg1, arg2);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadDumpPath(arg1) {
  return window['go']['main']['App']['LoadDumpPath'](arg1);
}

export function LoadDumpText(arg1) {
  return window['go']['main']['App']['LoadDumpText'](arg1);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function QueryAggregates(arg1) {
  return window['go']['main']['App']['QueryAggregates'](arg1);
}

export function QueryAggregatesRequest(arg1, arg2) {
  return window['go']['main']['App']['QueryAggregatesRequest'](arg1, arg2);
}

export function QueryLineage(arg1) {
  return window['go']['main']['App']['QueryLineage'](arg1);
}

export function QueryLineageChildren(arg1, arg2) {
  return window['go']['main']['App']['QueryLineageChildren'](arg1, arg2);
}

export function QueryLineageEvents(arg1, arg2) {
  return window['go']['main']['App']['QueryLineageEvents'](arg1, arg2);
}

export function QueryLineageGraph(arg1) {
  return window['go']['main']['App']['QueryLineageGraph'](arg1);
}

export function QueryLineageGraphSnapshot(arg1, arg2) {
  return window['go']['main']['App']['QueryLineageGraphSnapshot'](arg1, arg2);
}

export function QueryLineageRaw(arg1, arg2) {
  return window['go']['main']['App']['QueryLineageRaw'](arg1, arg2);
}

export function QueryLineageSnapshot(arg1, arg2) {
  return window['go']['main']['App']['QueryLineageSnapshot'](arg1, arg2);
}

export function QueryNewer(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryNewer'](arg1, arg2, arg3);
}

export function QueryPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryPage'](arg1, arg2, arg3);
}

export function QuerySearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['QuerySearch'](arg1, arg2, arg3);
}

export function QuerySnapshotPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QuerySnapshotPage'](arg1, arg2, arg3, arg4);
}

export function RawBySeqs(arg1) {
  return window['go']['main']['App']['RawBySeqs'](arg1);
}

export function RequiredPermissions(arg1) {
  return window['go']['main']['App']['RequiredPermissions'](arg1);
}

export function ResolveLineageAttribution(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveLineageAttribution'](arg1, arg2, arg3);
}

export function ResumeCapture() {
  return window['go']['main']['App']['ResumeCapture']();
}

export function RunLoginCommand(arg1) {
  return window['go']['main']['App']['RunLoginCommand'](arg1);
}

export function SaveAttributionSettings(arg1) {
  return window['go']['main']['App']['SaveAttributionSettings'](arg1);
}

export function SelectDumpFile() {
  return window['go']['main']['App']['SelectDumpFile']();
}

export function SetConnection(arg1) {
  return window['go']['main']['App']['SetConnection'](arg1);
}

export function SigmaRun(arg1) {
  return window['go']['main']['App']['SigmaRun'](arg1);
}

export function SigmaRunRequest(arg1, arg2) {
  return window['go']['main']['App']['SigmaRunRequest'](arg1, arg2);
}

export function SigmaSuite(arg1, arg2) {
  return window['go']['main']['App']['SigmaSuite'](arg1, arg2);
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}

export function TeardownCapture() {
  return window['go']['main']['App']['TeardownCapture']();
}

export function VerifyIdentity(arg1, arg2) {
  return window['go']['main']['App']['VerifyIdentity'](arg1, arg2);
}
