// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCaptureFilter(arg1) {
  return window['go']['main']['App']['ApplyCaptureFilter'](arg1);
}

export function CheckTrail(arg1, arg2) {
  return window['go']['main']['App']['CheckTrail'](arg1, arg2);
}

export function ClearEvents() {
  return window['go']['main']['App']['ClearEvents']();
}

export function ExportEventsJSON(arg1) {
  return window['go']['main']['App']['ExportEventsJSON'](arg1);
}

export function GetEventRaw(arg1) {
  return window['go']['main']['App']['GetEventRaw'](arg1);
}

export function GetInitialEvents() {
  return window['go']['main']['App']['GetInitialEvents']();
}

export function IngestFile(arg1) {
  return window['go']['main']['App']['IngestFile'](arg1);
}

export function IngestText(arg1) {
  return window['go']['main']['App']['IngestText'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function LoadDumpPath(arg1) {
  return window['go']['main']['App']['LoadDumpPath'](arg1);
}

export function LoadDumpText(arg1) {
  return window['go']['main']['App']['LoadDumpText'](arg1);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function QueryAggregates(arg1) {
  return window['go']['main']['App']['QueryAggregates'](arg1);
}

export function QueryLineage(arg1) {
  return window['go']['main']['App']['QueryLineage'](arg1);
}

export function QueryLineageChildren(arg1) {
  return window['go']['main']['App']['QueryLineageChildren'](arg1);
}

export function QueryLineageEvents(arg1) {
  return window['go']['main']['App']['QueryLineageEvents'](arg1);
}

export function QueryLineageGraph(arg1) {
  return window['go']['main']['App']['QueryLineageGraph'](arg1);
}

export function QueryNewer(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryNewer'](arg1, arg2, arg3);
}

export function QueryPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueryPage'](arg1, arg2, arg3);
}

export function RawBySeqs(arg1) {
  return window['go']['main']['App']['RawBySeqs'](arg1);
}

export function RequiredPermissions(arg1) {
  return window['go']['main']['App']['RequiredPermissions'](arg1);
}

export function RunLoginCommand(arg1) {
  return window['go']['main']['App']['RunLoginCommand'](arg1);
}

export function SelectDumpFile() {
  return window['go']['main']['App']['SelectDumpFile']();
}

export function SetConnection(arg1) {
  return window['go']['main']['App']['SetConnection'](arg1);
}

export function SigmaRun(arg1) {
  return window['go']['main']['App']['SigmaRun'](arg1);
}

export function StartCapture() {
  return window['go']['main']['App']['StartCapture']();
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}

export function TeardownCapture() {
  return window['go']['main']['App']['TeardownCapture']();
}

export function VerifyIdentity(arg1, arg2) {
  return window['go']['main']['App']['VerifyIdentity'](arg1, arg2);
}
